### ISSUE TITLE
tests depend on certain terminals

### ISSUE THREAD

**Issue by mess110** [dilcom/pilot-gnuplot#23]
On a new machine (ubuntu 14.04) tests fail when running rspec due to missing terminals. I installed gnuplot from source, and ran rspec https://gist.github.com/mess110/8921a931342a25999f78

On Travis, we are not getting the same behavior. Maybe because we are installing gnuplot from http://cz.archive.ubuntu.com/ubuntu vivid main universe

The tests should pass. Any ideas?

**Comment by ievgrafov** [comment]
I think tests are failed because absence of _qt_ terminal. There was the same issue when I tried to run tests on Mac OS. It may be solved by building Gnuplot with _--with-qt_ option.

I will remove requirement for this terminal from tests. This terminal isn't actually used in tests and now (when examples mostly are in notebooks) there is no need in it.

Thank you, it really should be fixed.
