### ISSUE TITLE
Document options for GnuplotRB::Plot.new in source code docs

### ISSUE THREAD

**Issue by v0dro** [dilcom/pilot-gnuplot#29]
It would be great to have the documentation (viz. the options that can be  passed and all their possible values and effects) in the source code docs itself, so that one does not need to hunt through the notebooks for figuring out usage all the time.

Also, if it could be possible to configure plots through some kind of a DSL, that would be great. It would also improve extensibility since I can just pass a configuration object to a daru user and she can do whatever she wants with it.

**Comment by ievgrafov** [comment]
I haven't added docs for options because they are covered in [gnuplot doc](http://www.gnuplot.info/docs_5.0/gnuplot.pdf)(pages 105-190). I'll add some (most often used in my opinion) of them to the docs but I don't think it's good idea to rewrite here all gnuplot's doc.

Couldn't you also provide some examples of DSL you want to use with gnuplotrb?

**Comment by v0dro** [comment]
Ok the most common can be documented. Also it would be great if there was a very visible link to GNU plot docs in the gnuplotRB docs somewhere.

I'm currently writing notebooks for daru using your gem, I'll post some DSL examples in a while.
